# Generated by Django 3.2.6 on 2022-06-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_featuredpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_baner', models.ImageField(null=True, upload_to='images/')),
                ('titel_baner', models.CharField(max_length=255)),
                ('description_baner', models.TextField(blank=True)),
                ('link', models.URLField(max_length=225, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FeaturedPost',
        ),
    ]
