# Generated by Django 3.2.6 on 2022-06-19 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20220619_0012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Baner',
        ),
    ]
