# Generated by Django 3.2.6 on 2022-06-23 02:29

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='FerWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleFer', models.CharField(max_length=255)),
                ('descriptionFer', tinymce.models.HTMLField()),
                ('img', models.ImageField(default='images/default.png', upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.URLField(default='https://www.youtube.com/embed/', max_length=300),
        ),
    ]
