# Generated by Django 3.2.6 on 2022-07-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20220626_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicationslinks',
            name='pinterest',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
